<?
	include $PATH_ABSOLUTE."includes/const/db.const.php";
	$map = array(
					$DB_ADMIN => array($DB_ADMIN_COL_LEVEL=>array($DB_ADMIN_LEVEL_COL_NAME)),
					$DB_CITY => array($DB_CITY_COL_STATE_ID=>array($DB_STATE_COL_NAME)),
					$DB_COUNTY => array($DB_COUNTY_COL_STATE_ID=>array($DB_STATE_COL_NAME)),
					$DB_JCP =>array($DB_JCP_COL_JUDGE_ID=>array($DB_JUDGE_COL_FIRST_NAME,$DB_JUDGE_COL_LAST_NAME),$DB_JCP_COL_CATEGORY_ID=>array($DB_CATEGORY_COL_NAME)),
					$DB_JGP =>array($DB_JGP_COL_JUDGE_ID=>array($DB_JUDGE_COL_FIRST_NAME,$DB_JUDGE_COL_LAST_NAME),$DB_JGP_COL_MIN_ID=>array($DB_GRADE_COL_NAME),$DB_JGP_COL_MAX_ID=>array($DB_GRADE_COL_NAME)),
					$DB_PROJECT =>array($DB_PROJECT_COL_PGL_ID=>array($DB_PGL_COL_LEVEL_NAME),$DB_PROJECT_COL_CATEGORY_ID=>array($DB_CATEGORY_COL_NAME),$DB_PROJECT_COL_BOOTH_ID=>array($DB_BOOTH_COL_NUMBER)),
					$DB_PGL =>array($DB_PGL_COL_MIN_ID=>array($DB_GRADE_COL_NAME),$DB_PGL_COL_MAX_ID=>array($DB_GRADE_COL_NAME)),
					$DB_SCHEDULE =>array($DB_SCHEDULE_COL_SESSION_ID=>array($DB_SESSION_COL_NUMBER,$DB_SESSION_COL_DATE,$DB_SESSION_COL_START,$DB_SESSION_COL_END),$DB_SCHEDULE_COL_PROJECT_ID=>array($DB_PROJECT_COL_TITLE),$DB_SCHEDULE_COL_JUDGE_ID=>array($DB_JUDGE_COL_FIRST_NAME,$DB_JUDGE_COL_LAST_NAME)),
					$DB_SCHOOL =>array($DB_SCHOOL_COL_CITY_ID=>array($DB_CITY_COL_NAME),$DB_SCHOOL_COL_COUNTY_ID=>array($DB_COUNTY_COL_NAME),$DB_SCHOOL_COL_STATE_ID=>array($DB_STATE_COL_NAME)),
					$DB_SCORE =>array($DB_SCORE_COL_JUDGE_ID=>array($DB_JUDGE_COL_FIRST_NAME,$DB_JUDGE_COL_LAST_NAME),$DB_SCORE_COL_PROJECT_ID=>array($DB_PROJECT_COL_TITLE)),
					$DB_STUDENT =>array($DB_STUDENT_COL_GRADE_ID=>array($DB_GRADE_COL_NAME),$DB_STUDENT_COL_GENDER_ID=>array($DB_GENDER_COL_NAME),$DB_STUDENT_COL_SCHOOL_ID=>array($DB_SCHOOL_COL_NAME),$DB_STUDENT_COL_PROJECT_ID=>array($DB_PROJECT_COL_TITLE)),
	);